[COD 39] connect backend and frontend for create cource
SchoolOfElvish/codeboard pull request #38
Opened 2023-03-11 11:11 UTC by SilaEwGenii

[JIRA ticket](https://legolas.atlassian.net/browse/COD-39)
Frontend
When creating a course, a message is entered about the creation of the course, which can be closed by clicking on the cross in the right corner of the message window.
<img width="1260" alt="Снимок экрана 2023-03-11 в 13 54 03" src="https://user-images.githubusercontent.com/102326057/224480694-4d764e91-023c-4f86-8a1a-a0311f81a609.png">

If you enter an incorrect value in the name field, the form is highlighted in red and displays an error pop-up message.
<img width="1280" alt="Снимок экрана 2023-03-11 в 13 54 25" src="https://user-images.githubusercontent.com/102326057/224480801-b6d4aff4-59de-42e2-81a4-b8a643285d22.png">

Backend
1. Changed error output from error.full_messages  to error.messages in controller courses and lessons.
2. Сreated a connection between frontend and backend.

2023-03-11 11:30 UTC, Set27 requested changes
Add i18n
"COD 39" to "COD-39"

2023-03-11 11:33 UTC, SilaEwGenii commented
> Добавить i18n "COD 39" в "COD-39"

sorry, thanks for the comment

2023-03-13 16:56 UTC, npupko requested changes
Let's add errors handler just in case

2023-03-14 21:48 UTC, SilaEwGenii commented
@Set27 , @npupko 
Good afternoon, the comments have been eliminated, I ask you to re-PR


1. [Added localization for the course creation page]

<img width="1435" alt="Снимок экрана 2023-03-15 в 00 42 44" src="https://user-images.githubusercontent.com/102326057/225147080-44b326cb-9ddc-4d23-9e62-0e8ff03b54b9.png">


2. [Display a course creation message]

<img width="1440" alt="Снимок экрана 2023-03-15 в 00 43 14" src="https://user-images.githubusercontent.com/102326057/225147463-0744fc9e-206a-4166-8fa1-f5fbcf3bee40.png">


3. [Error message display]

<img width="1440" alt="Снимок экрана 2023-03-15 в 00 43 39" src="https://user-images.githubusercontent.com/102326057/225147834-3127617b-45b9-4a4d-90db-9a9ae7807c10.png">

2023-03-15 19:29 UTC, Set27 approved these changes
lgtm

2023-03-16 14:02 UTC, npupko approved these changes
LGTM with small fixes

2023-03-16 14:02 UTC, npupko commented on frontend/src/lib/i18n/locales/en.json
> +      "create_button": "Create Course",
Let's be consistent and use same register for course everywhere.
I.e. if it's (Enter **course** name) than it should also be "Create **course**" (not Create **Course**), etc.
Downcase for course is ok there

2023-03-16 18:33 UTC, merged