[COD-38] fix group rout & connect backend and frontend [frontend]
SchoolOfElvish/codeboard pull request #41
Opened 2023-03-16 20:21 UTC by LorDEvilDead

2023-03-17 10:25 UTC, Set27 requested changes

2023-03-17 10:25 UTC, Set27 commented on frontend/src/lib/i18n/locales/ru.json
> +        "email": "Емеил должен быть заполнен"
Нет в русском языке слово Емеил
Лучше оставить "Email не может быть пустым"

2023-03-17 10:25 UTC, Set27 commented on frontend/src/routes/groups/new/+page.svelte
> +  let title: string;
так name или title? К чему этот плюрализм?

2023-03-17 10:25 UTC, Set27 commented on frontend/src/routes/groups/new/+page.svelte
> +      name: title
так name или title? К чему этот плюрализм?

2023-03-17 13:52 UTC, LorDEvilDead commented on frontend/src/lib/i18n/locales/ru.json
> +        "email": "Емеил должен быть заполнен"
> Нет в русском языке слово Емеил Лучше оставить "Email не может быть пустым"

По итогам разговора с Ником - я этот текст вообще удалю. По итогу емэил может быть пустым

2023-03-17 16:09 UTC, npupko commented on frontend/src/lib/i18n/locales/en.json
Please, fix localization for english version:
![image](https://user-images.githubusercontent.com/5938539/225958507-209505ca-79ae-4618-ba69-1d3d86644bc4.png)

2023-03-17 16:09 UTC, npupko commented on frontend/src/routes/groups/new/+page.svelte
> +  let title: string;
Let's consider using `name` everywhere

2023-03-18 08:40 UTC, Set27 approved these changes
LGTM

2023-03-19 19:14 UTC, SilaEwGenii approved these changes
LGTM

2023-03-20 11:00 UTC, npupko approved these changes
LGTM

2023-03-20 13:42 UTC, merged