[COD-37] Add bio about on profile page
SchoolOfElvish/codeboard pull request #47
Opened 2023-03-30 20:35 UTC by SilaEwGenii

Hello 
[JIRA ticket](https://legolas.atlassian.net/browse/COD-37)

https://user-images.githubusercontent.com/102326057/228958067-a33b908c-d3c3-402a-91de-af530c731477.mov

Frontend
1. Added an input field "About me"
2. Added output of values about me to the page of the show

Backend
1. Added a DD column to the user table
2. Added to the existing application logic

2023-04-03 15:52 UTC, npupko commented on frontend/src/routes/users/[id]/+page.svelte
> +                {#if about_info !== '' && about_info !== null}
Both `''` and `null` in js are `false` so you could just use `if (about_info)`

![image](https://user-images.githubusercontent.com/5938539/229562133-93246736-f3dc-4fb4-8f89-4226d8478363.png)

2023-04-03 15:52 UTC, npupko commented on frontend/src/routes/users/me/+page.ts
> +  about_info: string;
Let's make it `aboutInfo`

2023-04-03 18:55 UTC, Set27 requested changes

2023-04-03 18:55 UTC, Set27 commented on backend/app/controllers/api/v1/profiles_controller.rb
add i18n for backend

2023-04-03 21:48 UTC, SilaEwGenii commented on backend/app/controllers/api/v1/profiles_controller.rb
Oh thank you very much, otherwise I completely forgot that we were discussing this while you were writing this. By the way, why didn’t you write about conflicts? And then I'll forget.

2023-04-04 19:04 UTC, Set27 approved these changes

2023-04-06 15:05 UTC, npupko approved these changes
LGTM

2023-04-06 17:37 UTC, merged